name: Release a new version

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install gh CLI
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref }} \
            --title "Release ${{ github.ref }}" \
            --notes "Release ${{ github.ref }}" \
            --draft false \
            --prerelease false
